# Generated by Django 2.2.4 on 2019-08-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersclassroom',
            name='class_id',
            field=models.SlugField(default='454', max_length=10),
            preserve_default=False,
        ),
    ]
