# Generated by Django 2.2.4 on 2019-08-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersclassroom',
            old_name='tile',
            new_name='title',
        ),
    ]
