# Generated by Django 2.2.4 on 2019-08-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teachersclassroom_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersclassroom',
            name='class_id',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
