# Generated by Django 2.2.4 on 2019-08-04 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
