branch-defaults:
  default:
    environment: classroom-env
    group_suffix: null
  master:
    environment: classroom-env
global:
  application_name: classroom-app
  branch: null
  default_ec2_keyname: maroon-education
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
