# Generated by Django 2.2.4 on 2019-08-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='comment',
            field=models.CharField(max_length=150),
        ),
    ]
