# Generated by Django 2.2.4 on 2019-08-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='myassignments',
        ),
        migrations.AddField(
            model_name='student',
            name='my_classes',
            field=models.ManyToManyField(blank=True, to='teacher.TeachersClassRoom'),
        ),
    ]
