# Generated by Django 2.2.4 on 2019-08-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='myassignments',
            field=models.ManyToManyField(blank=True, to='assignment.Assignment'),
        ),
    ]
