# Generated by Django 2.2.4 on 2019-08-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_add_solution', 'can add solution to a assignment'), ('can_view_classroom', 'can view classroom page'), ('can_view_assignment', 'can view assignment'))},
        ),
    ]
