# Generated by Django 2.2.4 on 2019-08-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='myassignments',
            field=models.ManyToManyField(null=True, to='assignment.Assignment'),
        ),
    ]
