# Generated by Django 2.2.4 on 2019-08-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190804_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='myassignments',
            field=models.ManyToManyField(blank=True, to='assignment.Assignment'),
        ),
    ]
