# Generated by Django 2.2.4 on 2019-08-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190811_0148'),
        ('student', '0002_auto_20190811_1251'),
    ]

    operations = [
    ]
