# Generated by Django 2.2.4 on 2019-08-15 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190815_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^.{8}$')]),
        ),
    ]
