# Generated by Django 2.2.4 on 2019-08-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20190806_1832'),
        ('student', '0003_auto_20190807_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='SubmissionFile',
            new_name='SolutionFile',
        ),
    ]
