# Generated by Django 2.2.3 on 2019-08-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('year', models.CharField(blank=True, choices=[('', 'Select Year'), ('firstyear', 'First Year'), ('secondyear', 'Second Year'), ('thirdyear', 'Third Year'), ('fourthyear', 'Fourth Year')], default='', max_length=50, null=True)),
                ('branch', models.CharField(blank=True, choices=[('', 'Select Branch'), ('cse', 'Computer Engg.'), ('ee', 'Electrical Engg.'), ('ece', 'Electronics and Comm. Engg.'), ('me', 'Mechanical Engg.'), ('pie', 'Production and Industial Engg.'), ('ce', 'Civil Engg.')], default='', max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('rollno', models.CharField(max_length=10, null=True, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('myassignments', models.ManyToManyField(to='assignment.Assignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
