# Generated by Django 2.2.3 on 2019-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('user', '0002_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myassignments',
            field=models.ManyToManyField(to='assignment.Assignment'),
        ),
    ]
