# Generated by Django 2.2.4 on 2019-08-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assignment_of_class',
            new_name='classroom',
        ),
    ]
