# Generated by Django 2.2.4 on 2019-08-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190817_0024'),
        ('assignment', '0002_auto_20190816_2340'),
    ]

    operations = [
    ]
