# Generated by Django 2.2.4 on 2019-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20190811_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsfile',
            name='file',
            field=models.FileField(upload_to='assignment/files/'),
        ),
    ]
