# Generated by Django 2.2.4 on 2019-08-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20190812_1646'),
        ('assignment', '0003_auto_20190812_1647'),
    ]

    operations = [
    ]
