# Generated by Django 2.2.4 on 2019-08-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_merge_20190817_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
